name: Check for broken links in documentation

on:
  workflow_dispatch:
  push:

jobs:
  check-links:
    uses: ./.github/workflows/linkcheck.yml
    with:
      docs_path: docs
      issue_number: 1
      requirements_path: ./
