name: Check for broken links in documentation

on:
  workflow_dispatch:
  push:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install python
        run: pip install -r requirements.txt

      - name: Check links and open issue
        uses: ./.github/workflows/linkcheck
        with:
          docs_path: docs
          issue_number: 1
