name: Build documentation and check links

on:
  workflow_dispatch:
  push:

env:
  ISSUE_NUMBER: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      # By using `-q` linkcheck will treat broken links + missing refs as warnings
      # sphinxwarnings.txt will have text only if there are errors
      - name: Build the documentation
        run: |
          pip install -r requirements.txt
          sphinx-build docs docs/_build -w warnings.txt -q -b linkcheck
          # If there are warnings, set an environment variable that will open the issue
          [ -s sphinxwarnings.txt ] && echo -e "### Sphinx Warnings\n\n$(cat sphinxwarnings.txt)" > sphinxwarnings.txt && echo "HAS_ERRORS=TRUE" >> $GITHUB_ENV

      - name: Create issue from errors output
        if: env.HAS_ERRORS == 'TRUE'
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          issue-number: ${{env.ISSUE_NUMBER}}
          title: Broken links in documentation
          content-filepath: ./sphinxwarnings.txt

      - name: Re-open the links issue
        if: env.HAS_ERRORS == 'TRUE'
        run: gh issue reopen $ISSUE_NUMBER

