name: Build documentation and check links

on:
  workflow_dispatch:

env:
  ISSUE_NUMBER: 1

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Build the documentation
        run: |
          pip install -r requirements.txt
          sphinx-build docs docs/_build/html

      # ref: https://github.com/lycheeverse/lychee-action
      # ref: https://github.com/lycheeverse/lychee#commandline-parameters
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          # github.com link below: This is a known fail
          args: >
            docs/_build/**/*.html
            --insecure
            --max-retries 3
          jobSummary: true

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          issue-number: ${{ISSUE_NUMBER}}
          title: Broken links in documentation
          content-filepath: ./lychee/out.md

      - name: Re-open the links issue
        if: steps.lychee.outputs.exit_code != 0
        run: gh issue reopen ${{ISSUE_NUMBER}}

