name: Build documentation and check links

on:
  workflow_dispatch:
  push:

env:
  ISSUE_NUMBER: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Build the documentation
        continue-on-error: true  # So we'll trigger the next steps if job fails
        run: |
          pip install -r requirements.txt
          sphinx-build docs docs/_build/html -w sphinxwarnings.txt

      # ref: https://github.com/lycheeverse/lychee-action
      # ref: https://github.com/lycheeverse/lychee#commandline-parameters
      - name: Link check with Lychee
        uses: lycheeverse/lychee-action@v1.5.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          jobSummary: true
          args: >
            docs/_build/**/*.html
            --insecure
            --max-retries 3
        id: linkCheck

      # Detect output files from our previous two actions and open an issue if they exist
      - name: Concatenate warnings into one file
        run: |
          # Create an empty output file
          touch errors.md

          # If sphinx warnings is not empty, add it to the output file
          [ -s sphinxwarnings.txt ] && echo -e "### Sphinx Warnings:\n" >> errors.md && cat sphinxwarnings.txt >>  errors.md && echo -e "\n\n" >>  errors.md
          # If the lychee job fails, append its output to our errors
          [ -s lychee/out.md ] && cat lychee/out.md >>  errors.md
          # If errors is not empty, set environment variable
          [ -s errors.md ] && echo "HAS_ERRORS=TRUE" >> $GITHUB_ENV


      - name: Create issue from errors output
        if: env.HAS_ERRORS == 'TRUE'
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          issue-number: ${{env.ISSUE_NUMBER}}
          title: Broken links in documentation
          content-filepath: ./errors.md

      - name: Re-open the links issue
        if: env.HAS_ERRORS == 'TRUE'
        run: gh issue reopen $ISSUE_NUMBER

