name: Build documentation and check links

on:
  workflow_dispatch:
  push:

env:
  ISSUE_NUMBER: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install python
        run: pip install -r requirements.txt

      # By using `-q` linkcheck will treat broken links + missing refs as warnings
      # warnings.txt will have text only if there are errors
      - name: Build the documentation
        id: buildDocs
        continue-on-error: true
        run: |
          sphinx-build docs docs/_build -w warnings.txt -q -b linkcheck

      - name: Create issue from errors output
        if: steps.buildDocs.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          issue-number: ${{env.ISSUE_NUMBER}}
          title: Broken links in documentation
          content-filepath: ./warnings.txt

      - name: Re-open the links issue
        if: steps.buildDocs.outcome == 'failure'
        run: gh issue reopen $ISSUE_NUMBER

